name: blink
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    bundletool: /mnt/disco2/Programas/android-sdk/bundletool.jar
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
    export_apk: java -jar $bundletool build-apks --bundle=./build/app/outputs/bundle/release/app-release.aab --output=./build/app/outputs/bundle/release/app-release.apks --ks=blink.jks --ks-pass=pass:devv3rs@ --ks-key-alias=upload --key-pass=pass:devv3rs@

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  dio: ^3.0.1
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  #rxdart: ^0.22.1+1
  rxdart: ^0.25.0
  moor: ^3.0.0
  sqlite3_flutter_libs:
  sqflite: ^1.1.7 # Still used to obtain the database location
  path: ^1.7.0
  video_player: ^1.0.1
  http: ^0.12.2
  path_provider: ^1.6.27
  permission_handler: 4.4.0
  shared_preferences: ^0.4.3
  platform_device_id: ^0.1.3
  system_info: ^0.1.3
  #intl: ^0.17.0-nullsafety.2
  intl: ^0.16.0
  wifi: ^0.1.4
  battery: ^1.0.11
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  cross_connectivity: ^2.0.1
  flutter_svg: ^0.19.0
  archive: ^2.0.8
  onesignal_flutter: ^2.0.0
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.2
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.1
  moor_generator: 
  

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/teste.jpeg
    - assets/logo_versa.png


  fonts:
    - family: Arial
      fonts:
        - asset: fonts/arial.ttf
    - family: Calibri
      fonts:
        - asset: fonts/calibri-7.ttf
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Verdana
      fonts:
        - asset: fonts/verdana-4.ttf    
