name: blink
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    bundletool: /mnt/disco2/Programas/android-sdk/bundletool.jar
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
    export_apk: java -jar $bundletool build-apks --bundle=./build/app/outputs/bundle/release/app-release.aab --output=./build/app/outputs/bundle/release/app-release.apks --ks=blink.jks --ks-pass=pass:devv3rs@ --ks-key-alias=upload --key-pass=pass:devv3rs@

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^2.0.1
  #rxdart: ^0.22.1+1
  rxdart: ^0.27.1
  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  sqflite: ^2.0.0+3 # Still used to obtain the database location
  path: ^1.7.0
  video_player: ^2.1.6
  http: ^0.13.3
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  shared_preferences: ^2.0.6
  platform_device_id: ^1.0.1
  system_info: ^1.0.0
  #intl: ^0.17.0-nullsafety.2
  intl: ^0.17.0-nullsafety.2
  wifi: ^0.1.5
  battery: ^2.0.3
  connectivity: ^3.0.6
  data_connection_checker: ^0.3.4
  cross_connectivity: ^3.0.3
  flutter_svg: ^0.22.0
  archive: ^3.1.2
  onesignal_flutter: ^2.6.4
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  mobx_codegen: 2.0.1+3
  moor_generator: ^4.3.2
  build_runner: ^2.0.5

  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true

  assets:
    - assets/logo_versa.png


  fonts:
    - family: Arial
      fonts:
        - asset: fonts/arial.ttf
    - family: Calibri
      fonts:
        - asset: fonts/calibri-7.ttf
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Verdana
      fonts:
        - asset: fonts/verdana-4.ttf    
