enum DadosIdentificacao {
  NULO,
  PREVISAO_IMAGEM_TEMPO,
  TEMPLATE,
  CONTEUDO,
  CONTEUDO_AGENDAMENTO,
  NOTICIA,
  LOTERIA,
  PREVISAO_TEMPO,
  SEQUENCIA_CONTEUDO,
  CONTEUDO_VISUALIZADO,
  EQUIPAMENTO,
  
}